### ISSUE TITLE
Move default format to CDB_file

### ISSUE THREAD

**Issue by stdweird** [quattor/CCM#100]
Need to figure out if there is any reason not use CDB as default DB format (and if not, switch to it).

Related to https://github.com/quattor/aii/issues/175

Also requires change in default ccm.cfg in maven-tools

**Comment by jrha** [comment]
Agreed at workshop!

**Comment by piojo** [comment]
In addition to that, we'll make the CCM RPM depend on `perl-CDB_File`, so that during an upgrade nobody gets a new default but find themselves unable to run ccm-fetch because the required handler is not installed.

**Comment by ned21** [comment]
Confirming this works on EL5: $ rpm -q perl-CDB_File
perl-CDB_File-0.98-9.el5

**Comment by stdweird** [comment]
No change required in `maven-tools`, default is already CDB_File in the ccm.cfg
