### ISSUE TITLE
remove Element getUnescapedName

### ISSUE THREAD

**Issue by stdweird** [quattor/CCM#105]
I'm working on using unescaped (sub)paths for the CCM cli tools, but it would be nice to get rid of the `getUnescapedName` method from `Element`. i grepped the current code base, we do not use it anywhere, not even in unittests :smile:

**Comment by stdweird** [comment]
@ned21 @jrha @jouvin any objections?

**Comment by jouvin** [comment]
I tend to think this is a good move! I don't remember using it, at least in everything using the getTree() API. I you have not found any use of it in the whole code base, I've the feeling it is harmless to remove it. I guess that trying to build a release (running all the unit tests) after removing it should be enough to assess that we don't do any harm.

**Comment by jrha** [comment]
No objection.
