### ISSUE TITLE
remove context/context_time/context_ntime/profile_ntime

### ISSUE THREAD

**Issue by stdweird** [quattor/CCM#120]
unless someone knows what they are supposed to do.
from a first scan, it looks like at least the `_time` and `_ntime` options are not used.

**Comment by stdweird** [comment]
@ned21 @jrha @jouvin was this discussed? does it relate to #134?

**Comment by ned21** [comment]
Yes and not related to #134. ISTR when I looked at the "contexts" feature a little way back as a way of passing additional information from outside the profile, I found that the functionality no longer existed in any meaningful form. It seems pretty safe to remove any residual reference to them.
