### ISSUE TITLE
ccm-purge does not work

### ISSUE THREAD

**Issue by nowack73** [quattor/CCM#173]
At least in version 17.2 and 17.3, ccm-purge does not work. Calling it results in this error message:
```
Global symbol "$DIR" requires explicit package name at /usr/sbin/ccm-purge line 182.
Global symbol "$DIR" requires explicit package name at /usr/sbin/ccm-purge line 207.
Execution of /usr/sbin/ccm-purge aborted due to compilation errors.
```

The problem is line 177 of /usr/sbin/ccm-purge:
```perl
    if( !opendir(my $DIR , "${CacheDir}/$profile") ) {
```
This  results in a local variable $DIR that is valid only in the context of this if clause.

In order to use it in a broader context it has to be something like this:
```perl
    my $DIR;
    if( !opendir($DIR , "${CacheDir}/$profile") ) {
```

**Comment by stdweird** [comment]
@nowack73 thanks for reporting!
