### ISSUE TITLE
ccm must not depend on perl(Crypt::SSLeay) on RHEL 8

### ISSUE THREAD

**Issue by gombasg** [quattor/CCM#202]
`perl(Crypt::SSLeay)` does not exist anymore. Looking into the history of this dependency, I think it is needed only up to RHEL 6. On RHEL 7, `Crypt::SSLeay` is still available, but `libwww-perl` should not need it, so this dependency could be dropped on RHEL 7, too (I have not tested this, however).

Question is, how to handle OS version specific dependencies?

**Comment by stdweird** [comment]
for my tests, i rebuild perl CDB_File, Crypt-SSLeay, Config-Properties, LWP-Authen-Negotiate, -Crypt-OpenSSL-X509 and Set-Scalar (last one is already in epel testing).
these (maybe not all) used to be in eple6 and epel7, but not (yet?) in epel8. it's possible we don't need all those, but i think the bigger issue is that epel8 is not a full rebuild of epel7

**Comment by gombasg** [comment]
Well, I did something similar, except dropping Crypt-SSLeay :-) I'm planning to start requesting the missing packages in a couple weeks if they do not appear by then. If that does not work, they can still be added to the `quattor-externals` repository.

**Comment by stdweird** [comment]
i rebuild them based on latest fedora 31 src packages, it went smoothly so no real issue

**Comment by jrha** [comment]
We are now providing the package in http://yum.quattor.org/externals/noarch/el8/.
