### ISSUE TITLE
Unit test db failing: CDB_File missing

### ISSUE THREAD

**Issue by jouvin** [quattor/CCM#45]
`mvn test` on my SL6 machine fails because it requires `CDB_File`. I guess this is an optional package to use this backend. What is the package to add to a Quattor development machine for this to work? Is it worth adding this dependency for building CCM in the doc somewhere (I remember we had the same discussion about `metaconfig`). Is it worth adding it as RPM dependency also, to avoid problem at sites who may want to use this backend?

**Comment by stdweird** [comment]
use repoquery for all these (it's what the `build_all_repos.sh` script uses)
```
# repoquery --whatprovides 'perl(CDB_File)' 
perl-CDB_File-0:0.97-1.el6.x86_64
```
and then `yum info` (it's from EPEL apparently)

**Comment by jouvin** [comment]
Thanks. My real question was more about whether this is something we really want to support or that we deprecated and about the minimum documentation about these dependencies...

**Comment by stdweird** [comment]
If you want it deprecated/removed, i'm ok with that. but as long as it is not the case, there should be an explicit test to verify it works.
so for now, i would add this is as a package for the quattor development environment.

**Comment by stdweird** [comment]
@jouvin If you want `CDB_File` support removed or deprecated, i propose to open an issue for that and close this one?
