### ISSUE TITLE
15.2.0-rc5: ccm-fetch broken

### ISSUE THREAD

**Issue by jouvin** [quattor/CCM#46]
This is a showstopper for 15.2.0-rc5 (https://github.com/quattor/release/issues/81). After ugrading to new `ccm` version, any attempt to run `ncm-ccm` fails with the error below but `ccm-fetch` ran outside the component works fine. As there was almost no change to `ncm-ccm`since last release (only `NOQUATTOR` support), I tend to think the problem is in `CCM`

```
[INFO] running component: ccm
---------------------------------------------------------
[ERROR] failed to ccm-fetch with new config: Uncaught exception!!! Calling stack is:
  LC::Exception::throw_error called at /usr/lib/perl/EDG/WP4/CCM/CCfg.pm line 193
  EDG::WP4::CCM::CCfg::initCfg called at /usr/lib/perl/EDG/WP4/CCM/Fetch.pm line 161
  EDG::WP4::CCM::Fetch::_config called at /usr/lib/perl/EDG/WP4/CCM/Fetch.pm line 140
  EDG::WP4::CCM::Fetch::new called at /usr/sbin/ccm-fetch line 222
*** _readConfigFile(/proc/self/fd/0): non-existing config file /proc/self/fd/0

[INFO] configure on component ccm executed, 1 errors, 0 warnings
```

**Comment by stdweird** [comment]
already found the issue, it's a nice one...

**Comment by jouvin** [comment]
The most important is that it is nice!!! And BTW that you found it!

**Comment by jrha** [comment]
:grinning:
