### ISSUE TITLE
change to json_typed does not cause a re-fetch of profile

### ISSUE THREAD

**Issue by stdweird** [quattor/CCM#50]
When json_typed is enabled, the profile is not re-fetched and thus the DB stays in previous "state". 
Not sure if this is a bug or feature (and in any case easily fixed with `ccm-fetch --force`).

**Comment by jrha** [comment]
It's not a change to the profile contents per se, so this might be correct.
But on the other hand, the configuration on the node might change, so it should be re-applied...

**Comment by jouvin** [comment]
How it is enabled? I had expect this to happen through a change to /software/components/ccm. In this case, `ncm-ccm` could refetch with `--force` when there is a CCM config change... Even if this is generally not necessary, it should be harmless as CCM config changes are very rare IMO.

**Comment by stdweird** [comment]
For now, yes, it's via `ccm.conf`; but this is also an issue if it would become the default. we could allow some white list of options in `ncm-ccm` to trigger a fetch with `--force` (but there's something with that scenario; and i can't seem to find the discussion we once had about it when we did the NOQUATTOR support)

**Comment by jouvin** [comment]
What is the specific issue if it becomes the default? IMO, we should not try to implement a restricted list of options triggering `--force` (in fact it would be necessary only when the option is changed and this would be to difficult to implement) but rather to say that any change to the CCM options would trigger a `--force` in `ncm-ccm`. This would have the effect that at the **next modification** the new configuration will be used, wouldn't it?

**Comment by stdweird** [comment]
yes, this issue is to point out that currently, the changes only have effect with the next modification. 

the problem is that CCM has no internals to detect (let alone react to this change) that the internal DB changed with the same profile, so i'm afraid it might be quite a bit of work to properly fix the issue. but at least, now you know and have been warned :smile:

**Comment by jouvin** [comment]
Personnally, I tend to think that we should not try to address this one time issue... It should just be a warning in the documentation...

**Comment by jrha** [comment]
Agreed.
