### ISSUE TITLE
Support of Kerberos authentication in ccm-fetch

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/CCM#54]
LWP::UserAgent needs the plugin LWP::Authen::Negotiate in order to enable Kerberos authentication in case the profiles are in an Apache with mod_auth_kerb. This plugin is provided by the package perl-LWP-Authen-Negotiate. I suggest that this package is added in the "external" repositories, and it becomes a dependency of the ccm package.

**Comment by stdweird** [comment]
@StephaneGerardVUB what else is needed to make this work? if it is only a matter of adding the package, it could make it in 15.4 imho (the rpm exists in el5 EPEL); if more is needed, it will be 15.6.
@ned21 @gombasg any feedback (i was under the impression that MS used ccm with krb5)

**Comment by jrha** [comment]
It would be good to know! We plan migrate to kerberised ccm this year.

**Comment by stdweird** [comment]
now that i remember, i think this is related to https://github.com/quattor/CAF/issues/62 and the earlier discussion in https://github.com/quattor/aii/issues/81

**Comment by StephaneGerardVUB** [comment]
@stdweird You need something else for it to work : a valid kerberos ticket for root. root can always create a ticket using the keytab of the machine by doing "kinit -k -t /etc/krb5.keytab". So, what is missing is implementing ticket creation in ccm-fetch.

**Comment by jrha** [comment]
Ok, lets leave this for 15.6.

**Comment by stdweird** [comment]
tickets should be obtainable from perl, there's `Authen::Krb5` to help with that
@StephaneGerardVUB if you can live manuualy creating the tickets, maybe you can also add the dependency in the templates for now? i agree with @jrha that this can't be achieved for 15.4

**Comment by StephaneGerardVUB** [comment]
@stdweird Sure we can survive without that. You can postpone it to 15.6.

**Comment by ned21** [comment]
We don't use mod_auth_kerb but instead encrypt the profile such that only the intended recipient can decrypt it.

**Comment by jrha** [comment]
Did you patch ccm to do the decryption?

**Comment by ned21** [comment]
We don't have any local patches, if that's what you are asking, but I believe [this code in CCM](https://github.com/quattor/CCM/blob/master/src/main/perl/Fetch.pm#L633) originated from us.

**Comment by stdweird** [comment]
@ned21 any specific reason why you use that way of working instead of `mod_auth_kerb`?

**Comment by ned21** [comment]
Yes, several. One of them was that this provides encryption and authorisation via the same trust infrastructure. mod_auth_kerb requires SSL to ensure the data is not transmitted in the clear, plus management of appropriate ACLs on all the profile servers (of which we have many). Might be a good presentation at the next workshop if you are interested?

**Comment by jrha** [comment]
Yes please. What is doing the encryption?

**Comment by stdweird** [comment]
:+1: on the presentation
but aside from managing the trusts, no real technical reason? i think some sites are looking at a single realm setup, managed with freeipa; so if there's a technical drawback, that would be very interesting to know.

**Comment by ned21** [comment]
@jrha - a CGI script on the web server

@stdweird - depends on your definition of "technical". I don't think we considered mod_auth_kerb because it didn't (alone) meet the requirements we had, while kerberos encryption did.

**Comment by jrha** [comment]
Is this issue just a matter of documentation now?

**Comment by stdweird** [comment]
@jrha no, not really, i plan to fix this via https://github.com/quattor/CAF/pull/110. we need it end of january, so i'll work on it next month.

**Comment by stdweird** [comment]
@ned21 @gombasg what are the odds of MS accepting dependency on `LWP::Authen::Negotiate` in `CAF` or `CCM`? it is in epel, but even for el7 not in main repos. i could reimplement the code ofcourse (it's not that hard), but i'd prefer to avoid this kind of duplication.

**Comment by jnovy** [comment]
Hi Stijn,

it's ok as we can use EPEL now. perl-LWP-Authen-Negotiate is in all EPELs (version 0.08) so we should be good if you use this one.

Cheers,
Jindrich

**Comment by stdweird** [comment]
@jnovy thx!
