### ISSUE TITLE
ccm-fetch does not report updated profiles

### ISSUE THREAD

**Issue by stdweird** [quattor/CCM#75]
With https://github.com/quattor/CAF/pull/98, ccm-fetch is silent when updating (or with --force). It works (e.g. when `--verbose` is used), but maybe it should report something

**Comment by ned21** [comment]
Adding a "bug" label -- the old behaviour was useful in understanding if/when a host was updating.

**Comment by ned21** [comment]
@stdweird  Is this on your radar to fix? Does it depend on a future CAF change?

**Comment by stdweird** [comment]
@ned21 forgot about this one. i've tagged this 16.10, i can gave a quick look if this is an easy fix.

but as long as https://github.com/quattor/CAF/pull/98 is not merged, this output will still exist, but afaik, this has always been the output from `ccm-fetch` (it's more verbose now since all ccm files are generated by CAF, and the extra tabcompleiton line). but ccm-fetch never logged an updated profile before.
